apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-restore
  namespace: default
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: download-from-azure
        image: mcr.microsoft.com/azure-cli
        command: ["/bin/sh", "-c"]
        args:
          - |
            # Lister les blobs et récupérer le dernier fichier de sauvegarde
            BLOB_NAME=$(az storage blob list --account-name "moncomptebackup" --account-key "$AZURE_STORAGE_KEY" --container-name "backup-container" --query "[?starts_with(name, 'backup-')].name" -o tsv | sort -r | head -n 1)
            # Télécharger le fichier de sauvegarde depuis Azure
            az storage blob download --account-name "moncomptebackup" --account-key "$AZURE_STORAGE_KEY" --container-name "backup-container" --name "$BLOB_NAME" --file "/backup/$BLOB_NAME"
            # Sauvegarder le nom du blob dans un fichier temporaire
            echo "$BLOB_NAME" > /backup/blob_name.txt
        env:
          - name: AZURE_STORAGE_ACCOUNT
            value: "moncomptebackup"
          - name: AZURE_STORAGE_KEY
            valueFrom:
              secretKeyRef:
                name: azure-storage-secret
                key: value
          - name: AZURE_CONTAINER_NAME
            value: "backup-container"
        volumeMounts:
          - name: backup-storage
            mountPath: /backup

      - name: mysql-restore
        image: mysql:5.7
        command: ["/bin/sh", "-c"]
        args:
          - |
            # Attendre que le fichier de sauvegarde soit disponible
            until [ -f /backup/blob_name.txt ]; do echo "Waiting for blob name file..."; sleep 5; done
            # Lire le nom du fichier de sauvegarde
            BLOB_NAME=$(cat /backup/blob_name.txt)
            # Restaurer la base de données MySQL
            mysql -h mysql -P 3306 -u root -p${MYSQL_ROOT_PASSWORD} ${MYSQL_DATABASE} < /backup/$BLOB_NAME
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "pfa2024"  # Remplacez ceci par une méthode sécurisée dans un environnement de production
          - name: MYSQL_DATABASE
            value: "CodeWarrior"
        volumeMounts:
          - name: backup-storage
            mountPath: /backup

      volumes:
        - name: backup-storage
          persistentVolumeClaim:
            claimName: backup-pvcc  # Assurez-vous que ce PVC existe
