apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/EYABA12/code-warriors-pipline.git
    targetRevision: HEAD
    path: kuberntes
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
  # Définir les sous-applications ici
  sources:
    - repoURL: https://github.com/EYABA12/code-warriors-pipline.git
      path: kuberntes/mysql
      targetRevision: HEAD
      helm:
        valueFiles:
        - ../values/mysql-values.yml
    - repoURL: https://github.com/EYABA12/code-warriors-pipline.git
      path: kuberntes/microservice
      targetRevision: HEAD
      helm:
        valueFiles:
        - ../values/frontend-values.yml
    - repoURL: https://github.com/EYABA12/code-warriors-pipline.git
      path: kuberntes/microservice
      targetRevision: HEAD
      helm:
        valueFiles:
        - ../values/backend-values.yml
