apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: microservice-mysql-applicationset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - chartName: microservice
            repoURL: https://github.com/EYABA12/code-warriors-pipline.git
            path: microservice
            valueFiles:
              - backend-values.yml
              - frontend-values.yml
          - chartName: mysql
            repoURL: https://github.com/EYABA12/code-warriors-pipline.git
            path: mysql
            valueFiles:
              - values.yaml
  template:
    metadata:
      name: "{{chartName}}-application"
    spec:
      project: default
      source:
        repoURL: "{{repoURL}}"
        path: "{{path}}"
        helm:
          valueFiles:
            - "{{valueFiles}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true
