
appName: mysql
appImage: mysql
appVersion: 8.0.39-debian
appReplicas: 1
containerPort: 3306
volumeName: mysql-data
containerMountPath: /data
containerEnvVars:
  - name: MYSQL_ROOT_PASSWORD
    value: "pfa2024"  # Mot de passe root
  - name: MYSQL_DATABASE
    value: "CodeWarrior"  # Nom de la base de données
servicePort: 3306
